'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

module.exports=async function({application,page,nativeState,nativeWait,hostWait,pass,evidence}) {
  const request=(url,body)=>page.evaluate(([u,b])=>api(u,b),[url,body]);
  const pause=()=>new Promise(resolve=>setTimeout(resolve,100));
  const pot=67169062,choice=74191942,ash=14558127,draw=55144522,monster=1184620;
  const hand=[choice,choice,pot,draw,monster,monster];
  const deck={main:[...hand,...Array(34).fill(monster)],extra:[],side:[]};
  const source=await request('/api/decks',{name:'妥协场隔离验收-'+Date.now(),deck});
  const sourceBefore=await request('/api/deck?id='+encodeURIComponent(source.id));
  await page.evaluate(async()=>{switchView('training');await syncNativeHost();});
  const started=await request('/api/start',{deck_id:source.id,design:{name:'贪欲之壶的妥协分支',notes:'隔离验收',deck,deck_name:source.name,
    conditions:{hand_count:hand.length,slots:hand,banned:[]},opponent_ai:false}});
  let sid=started.id;
  await page.evaluate(()=>refreshHistory());await hostWait(sid,s=>s.frame_ready);await nativeWait(sid,s=>s.prompt===11);
  async function activate(code) {
    let s=await nativeWait(sid,s=>s.prompt===11&&s.activatable.includes(code));
    await nativeState(sid,'click',s.targets.find(t=>t.code===code&&t.location===2));
    s=await nativeWait(sid,s=>s.buttons.some(b=>b.text==='发动'));
    await nativeState(sid,'click',s.buttons.find(b=>b.text==='发动'));
    s=await nativeWait(sid,s=>s.prompt===18);await nativeState(sid,'click',s.targets.find(t=>t.location===8&&!t.code));
  }
  async function selectFive() {
    await nativeWait(sid,s=>s.prompt===15&&s.choices.length>=5);
    for(let i=0;i<40;i++) {
      const state=await nativeState(sid);if(state.prompt===11)return;
      const card=state.choices.find(c=>!c.selected);
      const ok=state.buttons.find(b=>b.text==='确定');if(ok)await nativeState(sid,'click',ok);else if(card)await nativeState(sid,'click',card);else await pause();
    }
    throw new Error('Five-card effect did not settle');
  }
  await activate(choice);await selectFive();
  await activate(choice);await selectFive();
  const beforePot=await request('/api/report/'+sid);
  assert.equal(beforePot.final_state.cards.filter(c=>c.controller===0&&c.location===16&&c.code===monster).length,8);
  await activate(pot);await selectFive();
  const mainId=sid;
  await page.locator('#finish-training').click();
  await page.waitForFunction(()=>!app.active&&!!flow.draft&&!flow.busy,null,{timeout:20000});
  const main=await request('/api/report/'+mainId);
  assert.equal(main.statistics['效果抽卡'],2);
  const point=main.branch_points.find(p=>p.timing==='发动后的响应窗口'&&p.cards.some(c=>c.code===pot));assert(point,'Avarice must have a recorded legal response checkpoint');
  assert.equal(await page.locator('#nav-compromise').isDisabled(),true);
  await require('./branch-menu-smoke.cjs')({page,application,main,point,pass,evidence});
  const choosePoint=async()=>{
    await page.evaluate(id=>showReport(id),mainId);
    await page.locator(`#review-steps [data-review-node="${point.node_id}"]`).click({button:'right'});
    await page.locator('#branch-context-menu').waitFor({state:'visible'});
    await page.locator('#branch-point').selectOption(String(point.checkpoint));
    await page.locator('#create-compromise').click();
    await page.waitForFunction(()=>app.view==='compromise'&&!branchUI.busy);
  };
  await choosePoint();assert.equal(await page.locator('#nav-compromise').isEnabled(),true);
  const firstId=await page.evaluate(()=>branchUI.selected);
  await page.locator('#branch-search').fill('灰流丽');
  await page.locator(`[data-branch-add="${ash}"]`).click();
  await page.locator(`[data-branch-count="${ash}"]`).fill('2');
  await page.locator(`[data-branch-count="${ash}"]`).dispatchEvent('change');
  await page.locator('#branch-name').fill('灰流丽无效后继续');
  await page.evaluate(()=>saveBranchConfiguration());
  let workspace=await request('/api/report/'+mainId);
  assert.deepEqual(workspace.actions,main.actions);assert.deepEqual(workspace.final_state,main.final_state);
  assert.deepEqual(workspace.branches[0].premises,[]);assert.equal((await request('/api/plans')).some(p=>p.id===mainId),false);
  await page.locator('#branch-return').click();await page.locator('#review-branch-view').check();
  assert.equal(await page.evaluate(()=>reviewUI.report.final_state),null);
  assert.equal(await page.locator('#review-step-notes').isDisabled(),true);
  await page.locator('#review-branch-view').uncheck();await page.locator('#nav-compromise').click();
  await page.screenshot({path:path.join(evidence,'compromise-setup.png')});
  pass('Valid timeline checkpoint enables branch setup; configured Ash is isolated and does not become an observed interference or formal plan');
  const opened=application.waitForEvent('window',{timeout:60000});await page.locator('#branch-enter').click();
  await page.waitForFunction(()=>!branchUI.busy,null,{timeout:50000});
  const enterStatus=await page.evaluate(()=>document.querySelector('#notice').textContent);
  assert(!enterStatus.includes('失败')&&!enterStatus.includes('无法'),enterStatus);
  const opponent=await opened;await opponent.waitForFunction(()=>typeof opponentState!=='undefined'&&opponentState.state?.manual&&opponentState.state?.player===1,null,{timeout:60000});
  sid=await page.evaluate(()=>app.active.id);
  assert.notEqual(sid,mainId);
  assert.equal(await opponent.evaluate(()=>opponentState.id),sid);
  await opponent.locator('[data-opponent-choice]').first().waitFor();
  const opponentPng=await application.evaluate(async({BrowserWindow})=>{
    const contents=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('/opponent.html')).webContents;
    await contents.capturePage(undefined,{stayHidden:true});await new Promise(resolve=>setTimeout(resolve,150));
    return (await contents.capturePage(undefined,{stayHidden:true})).toPNG().toString('base64');
  });fs.writeFileSync(path.join(evidence,'compromise-opponent.png'),Buffer.from(opponentPng,'base64'));
  const version=await opponent.evaluate(()=>typeof opponentState!=='undefined'&&opponentState.state.version);
  await opponent.evaluate(()=>submitOpponent('answer',opponentInt(999)));
  await opponent.waitForFunction(previous=>opponentState.state.version>previous&&opponentState.state.manual,version);
  await assert.rejects(request('/api/opponent/control',{id:sid,command:'answer',version,raw:'00000000'}));
  await opponent.locator('[data-opponent-choice]').filter({hasText:'灰流丽'}).first().click();
  await nativeWait(sid,s=>s.prompt===11);
  let branch=await request('/api/report/'+sid);
  const avarice=branch.actions.find(a=>a.kind==='effect'&&a.cards.some(c=>c.code===pot));
  assert.equal(avarice.status,'disabled');assert.equal(branch.statistics['效果抽卡'],0);
  const ashEffect=branch.actions.find(a=>a.kind==='effect'&&a.cards.some(c=>c.code===ash));
  assert(ashEffect.results.some(r=>r.message===76&&r.cards.some(c=>c.code===pot)));
  assert(branch.events.some(e=>e.message==='对手手动选择'));
  assert(!branch.actions.some(a=>a.evidence_refs.every(ref=>branch.events.find(e=>e.id===ref)?.message==='对手手动选择')));
  assert.equal(branch.final_state.cards.filter(c=>c.location===16&&c.code===monster).length,8);
  const branchTimeline=await request('/api/timeline/'+sid);
  const inherited=branchTimeline.nodes.filter(n=>n.id<=point.checkpoint);
  assert(inherited.length&&inherited.every(n=>n.restorable===false));
  await assert.rejects(request('/api/rewind',{id:sid,node:inherited[0].id,revision:branchTimeline.revision}));
  const responded=(await request('/api/report/'+mainId)).branches.find(b=>b.id===firstId);
  assert(responded.premises.some(p=>p.confirmed&&p.result==='效果被无效'&&p.source_cards.some(c=>c.code===ash)&&p.affected_cards.some(c=>c.code===pot)));
  pass('The same live duel legally resolves Ash against Avarice; its five targets stay in the graveyard, no mainline draws leak into the branch, and causal evidence is recorded');
  for(let i=0;i<2;i++) {
    await opponent.locator('#opponent-release').click();await opponent.waitForFunction(()=>!opponentState.state.manual);
    await page.locator('#take-opponent').click();await opponent.waitForFunction(()=>typeof opponentState!=='undefined'&&opponentState.state.manual);
  }
  const closing=opponent.waitForEvent('close');await opponent.locator('#opponent-close').click();await closing;
  assert((await request('/api/opponent/state/'+sid)).running);
  const reopened=application.waitForEvent('window');await page.locator('#take-opponent').click();
  const secondWindow=await reopened;
  assert(secondWindow);await secondWindow.waitForFunction(()=>typeof opponentState!=='undefined'&&opponentState.state?.manual);
  await activate(draw);
  await nativeWait(sid,s=>s.prompt===11);
  // A second Ash remains in hand, but its player-wide once-per-turn limit
  // survives all handovers and prevents another response to the continuation.
  branch=await request('/api/report/'+sid);assert.equal(branch.statistics['效果抽卡'],2);
  assert.equal(branch.final_state.cards.filter(c=>c.controller===1&&c.location===2&&c.code===ash).length,1);
  assert.equal(branch.actions.filter(a=>a.kind==='effect'&&a.cards.some(c=>c.code===ash)).length,1);
  await page.locator('#finish-training').click();await page.waitForFunction(()=>!app.active&&!flow.busy&&branchUI.root?.id===app.reportId,null,{timeout:20000});
  await secondWindow.close();
  assert.equal(await page.evaluate(()=>branchUI.viewing),true);
  await page.locator('#review-steps [data-review-node="final"]').click({button:'right'});
  assert.equal(await page.locator('#create-compromise').isDisabled(),true);
  assert((await page.locator('#branch-context-status').innerText()).includes('子分支'));
  await page.locator('#branch-context-cancel').click();
  await page.locator('#review-steps [data-review-node="final"]').click();
  await page.locator('#review-step-notes').fill('灰流丽无效后改用强欲之壶续展。');
  await page.locator('#draft-name').fill('贪欲之壶：主线与妥协场');
  pass('Repeated takeover and AI handover retain the current engine, effect limits and complete operation journal; closing the opponent window leaves the duel running');
  await choosePoint();const secondId=await page.evaluate(()=>branchUI.selected);
  await page.locator('#branch-name').fill('具备灰流丽但选择不发动');
  await page.locator('#branch-search').fill('灰流丽');await page.locator(`[data-branch-add="${ash}"]`).click();
  const openedAgain=application.waitForEvent('window');await page.locator('#branch-enter').click();
  const alternative=await openedAgain;await alternative.waitForFunction(()=>typeof opponentState!=='undefined'&&opponentState.state?.manual&&opponentState.state?.player===1,null,{timeout:60000});
  sid=await page.evaluate(()=>app.active.id);
  await alternative.locator('[data-opponent-choice]').filter({hasText:'放弃本次响应'}).click();await nativeWait(sid,s=>s.prompt===11);
  const alternate=await request('/api/report/'+sid);assert.equal(alternate.statistics['效果抽卡'],2);
  await page.locator('#finish-training').click();await page.waitForFunction(()=>!app.active&&!flow.busy,null,{timeout:20000});await alternative.close();
  workspace=await request('/api/report/'+mainId);
  assert.equal(workspace.branches.length,2);assert.equal(workspace.branches[1].premises.length,0);
  assert.deepEqual(workspace.actions,main.actions);assert.deepEqual(workspace.final_state,main.final_state);
  const resources=await request(`/api/branch-resources/${mainId}?branch=${firstId}`);
  assert(resources.additional.main.some(c=>c.code===draw&&c.count===1));
  assert(!resources.combined.main.some(c=>c.code===ash));
  assert(!(await request(`/api/branch-resources/${mainId}?branch=${secondId}`)).additional.main.some(c=>c.code===draw));
  await page.locator('#save-plan').click();await page.waitForFunction(()=>!!reviewUI.pending&&!flow.busy);
  assert.equal(await page.evaluate(()=>reviewUI.pending.branches.length),2);
  await page.locator('#confirm-save-plan').click();await page.waitForFunction(()=>!flow.busy&&app.view==='plans');
  const saved=await request('/api/plan/'+mainId);assert.equal(saved.branches.length,2);assert.deepEqual(saved.actions,main.actions);
  assert.equal(saved.name,'贪欲之壶：主线与妥协场');
  assert.equal(saved.branches[0].report.annotations.nodes.final.notes,'灰流丽无效后改用强欲之壶续展。');
  assert.notEqual(saved.annotations.nodes.final?.notes,'灰流丽无效后改用强欲之壶续展。');
  const shared=await request('/api/plan-export/'+mainId);
  assert.equal(shared.plan.branches.length,2);
  assert(!JSON.stringify(shared).includes('replay_sha256'));assert(!JSON.stringify(shared).includes('session_id'));
  await request('/api/plans/import-preview',{document:shared});
  assert.equal(await page.locator('#saved-branch-view').isChecked(),false);
  await page.locator('#saved-branch-select').selectOption(firstId);await page.locator('#saved-branch-resources').check();
  assert.equal(await page.locator('#saved-branch-view').isChecked(),false);
  await page.locator('#saved-branch-view').check();assert((await page.locator('#saved-branch-panel').innerText()).includes('效果被无效'));
  await page.screenshot({path:path.join(evidence,'compromise-saved.png')});
  await page.locator('#saved-branch-select').selectOption(secondId);assert(!(await page.locator('#saved-branch-panel').innerText()).includes('效果被无效'));
  await page.evaluate(async id=>{await showPlan(id);await showReport(id);},mainId);
  assert.equal(await page.locator('#review-branch-view').isChecked(),false);
  await page.evaluate(id=>showPlan(id),mainId);await page.locator('#generate-plan-tutorial').click();
  assert.equal(await page.locator('[data-branch-connection]').count(),0);
  await page.locator('#tutorial-include-branches').check();
  assert.equal(await page.locator('[data-branch-connection]').count(),2);
  for(const line of await page.locator('[data-branch-connection]').all())assert.equal(await line.getAttribute('data-source-checkpoint'),String(point.checkpoint));
  const svg=await page.evaluate(async()=>{const {model,layout}=planTutorialUI;return renderPlanTutorialSvg(model,layout,await tutorialAssets(model));});
  assert(!svg.includes('href="/pics/'));fs.writeFileSync(path.join(evidence,'compromise-flow.svg'),svg);
  assert(!svg.includes('对手手动选择'),'Control inputs stay in raw records instead of becoming effect steps in the tutorial');
  const png=await page.evaluate(async()=>{
    const {model,layout}=planTutorialUI,svg=renderPlanTutorialSvg(model,layout,await tutorialAssets(model));
    const bytes=new Uint8Array(await (await tutorialPng(svg,layout)).arrayBuffer());let binary='';
    for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary);
  });
  const pngBytes=Buffer.from(png,'base64');assert.equal(pngBytes.subarray(1,4).toString(),'PNG');fs.writeFileSync(path.join(evidence,'compromise-flow.png'),pngBytes);
  await page.locator('#plan-tutorial-close').click();
  assert.deepEqual(await request('/api/deck?id='+encodeURIComponent(source.id)),sourceBefore);
  fs.writeFileSync(path.join(evidence,'compromise-verification.json'),JSON.stringify({mainId,branchIds:[firstId,secondId],point,resources,saved},null,2));
  pass('Two branches save inside one plan, reopen on the mainline, switch complete route/end-board data, count only selected extra player resources, and export precise branch arrows with embedded card images');
  return {id:mainId,branch:firstId};
};
