'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

module.exports=async({page,application,root,evidence,pass})=>{
  page.setDefaultTimeout(30000);
  const before=await page.evaluate(async()=>({decks:await api('/api/decks'),intel:await api('/api/intelligence'),tags:await api('/api/tags')}));
  const command=body=>page.evaluate(body=>api('/api/knowledge',body),body);
  const settled=()=>page.waitForFunction(()=>!knowledgeUI.busy&&!moduleUI.switching);
  await page.locator('#module-knowledge').click();
  await page.waitForFunction(()=>moduleUI.current==='knowledge'&&!!knowledgeUI.snapshot&&!moduleUI.switching);
  await page.locator('#knowledge [data-k-action="tab"][data-tab="projects"]').click();
  await page.locator('[data-k-action="project-sample"]').click();
  await page.waitForFunction(()=>!!knowledgeUI.project&&!knowledgeUI.busy);
  const initial=await page.evaluate(()=>structuredClone(knowledgeUI.project));
  assert.equal(initial.inspection.counts.build,2);assert.equal(initial.inspection.counts.route,2);
  assert.equal(initial.inspection.counts.branch,1);assert.equal(initial.inspection.counts.countermeasure,1);
  assert.equal(initial.inspection.capabilities.execute,false);
  await page.locator('#knowledge-record-list [data-id="route-1-s02"]').click();
  await page.locator('[data-k-bind="data.costs"]').fill('验收修订：按实际来源核对已支付费用');
  await page.locator('#knowledge-save').click();await settled();
  let project=await command({op:'project.get',id:initial.id});
  assert.equal(project.document.records['route-1-s02'].revision,2);
  assert.deepEqual(project.document.records['source-decks'],initial.document.records['source-decks']);
  assert(project.impact===undefined||project.impact.reused.includes('route-2'));
  assert.equal(typeof project.document.records['route-1-s02'].data.cards[0],'number');
  await page.locator('[data-k-action="review-human"]').click();await settled();
  assert.equal(await page.evaluate(()=>knowledgeUI.project.inspection.checks.at(-1).state),'passed');
  await page.screenshot({path:path.join(evidence,'knowledge-project.png')});
  pass('Editable project preserves original evidence, uses stable numeric cards and revisions, and binds human checks to dependencies');

  // Capture this application's Blob download without invoking a system Save dialog.
  await page.evaluate(()=>{
    window.knowledgeDownloads=[];const original=URL.createObjectURL;
    URL.createObjectURL=function(blob){if(blob.type==='application/json')blob.text().then(text=>window.knowledgeDownloads.push(JSON.parse(text)));return original.call(this,blob);};
    document.addEventListener('click',event=>{if(event.target.closest('a[download]')?.download.includes('知识包'))event.preventDefault();},true);
  });
  await page.locator('#knowledge-publish-version').fill('1.0.0');
  await page.locator('#knowledge-publish').click();
  await page.locator('.knowledge-confirm [data-c="ok"]').click();
  await page.waitForFunction(()=>knowledgeDownloads.length===1&&!knowledgeUI.busy);
  const bundle=await page.evaluate(()=>knowledgeDownloads[0]);const pid=bundle.document.package.id;
  await page.locator('#knowledge [data-k-action="tab"][data-tab="installed"]').click();
  async function installFile(value){
    await page.setInputFiles('#knowledge-install-input',{name:'branded.知识包.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});
    await page.waitForFunction(()=>!!knowledgeUI.installPreview&&!knowledgeUI.busy);
    await page.locator('[data-k-action="install-confirm"]').click();await settled();
  }
  await installFile(bundle);
  const installed=await page.evaluate(()=>structuredClone(knowledgeUI.snapshot));
  assert.equal(installed.packages.find(p=>p.id===pid).enabled,false);
  await page.locator(`[data-k-action="package-open"][data-id="${pid}"]`).click();await settled();
  await page.locator('[data-k-action="package-enable"]').click();await settled();
  assert.equal(await page.evaluate(pid=>knowledgeUI.snapshot.packages.find(p=>p.id===pid).enabled,pid),true);
  const repeatBefore=await page.evaluate(()=>api('/api/knowledge'));
  await command({op:'package.install',bundle,digest:bundle.digest,revision:repeatBefore.revision});
  assert.deepEqual(await page.evaluate(()=>api('/api/knowledge')),repeatBefore);
  await page.locator('#module-decks').click();
  await page.waitForFunction(()=>moduleUI.current==='decks'&&!moduleUI.switching);
  await page.waitForFunction(()=>document.querySelectorAll('#knowledge-deck-shelf [data-k-action="shelf-open"]').length===2);
  await page.locator('#knowledge-deck-shelf [data-k-action="shelf-open"]').first().click();await settled();
  await page.waitForFunction(()=>moduleUI.current==='knowledge'&&knowledgeUI.selected==='build-1');
  await page.locator('#knowledge-record-list [data-id="route-1"]').click();
  await page.locator('#knowledge .knowledge-main [data-k-action="record-select"][data-id="route-1-s02"]').first().click();
  await page.locator('#knowledge .knowledge-main [data-k-action="record-select"][data-id="compromise-1"]').first().click();
  assert((await page.locator('#knowledge .knowledge-main').innerText()).includes('剩余')||(await page.locator('#knowledge .knowledge-main').innerText()).includes('保留'));
  await page.screenshot({path:path.join(evidence,'knowledge-installed.png')});
  pass('Publish, file-preview, disabled installation, enable, idempotent reinstall, deck shelf and step-to-compromise navigation work in the real renderer');

  await page.locator('#knowledge-record-list [data-id="route-1-s02"]').click();
  await page.locator('[data-k-action="overlay-edit"]').click();
  await page.locator('#knowledge-editor [data-k-bind="title"]').fill('我的步骤标题 <script>不执行</script>');
  await page.locator('[data-k-action="overlay-save"]').click();
  await page.locator('.knowledge-confirm input[type="text"]').fill('个人批注保留');
  await page.locator('.knowledge-confirm [data-c="ok"]').click();await settled();
  assert.equal(await page.locator('#knowledge script').count(),0);
  const local=await command({op:'package.get',package_id:pid,version:'1.0.0'});
  assert.equal(local.personal_notes['route-1-s02'],'个人批注保留');
  project=await command({op:'project.get',id:initial.id});
  project.document.records['route-1-s02'].title='新版步骤标题';
  project.document.records['route-1-s02'].data.costs='新版费用说明';
  const nextProject=await command({op:'project.save',id:project.id,revision:project.revision,document:project.document});
  assert(nextProject.impact.affected.includes('route-1'));
  assert(nextProject.impact.reused.includes('route-2'));
  assert(nextProject.inspection.checks.some(c=>c.state==='stale'));
  const newer=await command({op:'project.publish',id:project.id,revision:nextProject.revision,version:'1.1.0'});
  await page.locator('[data-k-action="package-back"]').click();
  await installFile(newer);
  await page.locator(`[data-k-action="package-open"][data-id="${pid}"]`).click();await settled();
  await page.locator('[data-k-role="package-version"]').selectOption('1.1.0');
  await page.locator('[data-k-action="package-enable"]').click();await settled();
  assert(await page.locator('[data-k-action="conflict-activate"]').isVisible());
  assert.equal((await page.evaluate(()=>api('/api/knowledge'))).packages.find(p=>p.id===pid).active,'1.0.0');
  await page.screenshot({path:path.join(evidence,'knowledge-conflict.png')});
  await page.locator('[data-k-action="conflict-activate"]').click();await settled();
  let current=await command({op:'package.get',package_id:pid});
  assert.equal(current.document.package.version,'1.1.0');
  assert.equal(current.document.records['route-1-s02'].title,local.document.records['route-1-s02'].title);
  assert.equal(current.document.records['route-1-s02'].data.costs,'新版费用说明');
  assert.equal(current.index.statistics.generated,1);
  assert.equal((await command({op:'package.get',package_id:pid,version:'1.0.0'})).document.records['route-1-s02'].data.costs,'验收修订：按实际来源核对已支付费用');
  pass('Update identifies affected routes, invalidates old checks, reuses unchanged indexes, keeps pinned v1 and requires explicit personal-conflict resolution');

  await page.locator('[data-k-role="package-version"]').selectOption('1.0.0');
  await page.locator('[data-k-action="package-enable"]').click();await settled();
  if(await page.locator('[data-k-action="conflict-activate"]').count()){await page.locator('[data-k-action="conflict-activate"]').click();await settled();}
  assert.equal((await command({op:'package.get',package_id:pid})).document.package.version,'1.0.0');
  await page.locator('[data-k-action="package-disable"]').click();await settled();
  assert.equal((await command({op:'catalog'})).length,0);
  await page.locator('[data-k-action="package-uninstall"]').click();
  await page.locator('#flow-confirm').click();await settled();
  current=await command({op:'package.get',package_id:pid,version:'1.0.0'});
  assert.equal(current.personal_notes['route-1-s02'],'个人批注保留');
  const after=await page.evaluate(async()=>({decks:await api('/api/decks'),intel:await api('/api/intelligence'),tags:await api('/api/tags')}));
  assert.deepEqual(after,before);
  const projects=await command({op:'project.get',id:initial.id});
  fs.writeFileSync(path.join(evidence,'knowledge-acceptance.json'),JSON.stringify({counts:initial.inspection.counts,project:projects.id,revision:projects.revision,activeVersion:'1.0.0',personalPreserved:true,originalDataUnchanged:true,globalInput:false,trainingStarted:false},null,2));
  pass('Rollback, disable and uninstall preserve personal overlays, project source evidence, existing decks/TAG/intelligence, and historical source versions');
};
