'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');

module.exports=async function({page,report,pass,evidence}) {
  const nodes=report.review.nodes;
  assert(report.review.complete,'Real engine journal must provide complete review states');
  assert.equal(await page.locator('#history #history-list').count(),0);
  let engineWrites=0;
  const observer=request=>{if(/\/api\/(start|rewind|native\/test)$/.test(request.url())&&request.method()==='POST')engineWrites++;};
  page.on('request',observer);
  const select=async id=>{
    await page.locator('#review-steps [data-review-node]').filter({has:page.locator('span')}).evaluateAll((buttons,id)=>buttons.find(b=>b.dataset.reviewNode===id).click(),id);
    await page.waitForFunction(id=>reviewUI.node===id,id);
  };
  for(const node of [...nodes,...nodes.slice().reverse()]) {
    await select(node.id);
    const cards=node.state.cards.filter(c=>c.controller===0);
    const expected=cards.filter(c=>c.location===2).length;
    assert.equal(await page.locator('.own-board .review-hand .review-card').count(),expected);
    assert.equal(await page.locator('.own-board .monster-slot .review-card').count(),cards.filter(c=>c.location===4&&c.sequence<5&&!c.overlay_target).length);
    assert.equal(await page.locator('.opponent-board').count(),0);
  }
  await page.locator('#review-sidebar-toggle').click();
  assert(await page.locator('#review-workspace').evaluate(el=>el.classList.contains('sidebar-collapsed')));
  await page.locator('#review-sidebar-toggle').click();
  await select('initial');
  await page.locator('#current-node-title').click();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.evaluate(()=>reviewUI.node),nodes[1].id);
  await page.locator('[data-review-zone="0:16"]').click();
  assert.equal(await page.locator('#review-zone-content').evaluate(el=>getComputedStyle(el).position),'fixed');
  await page.keyboard.press('Escape');
  assert(await page.locator('#review-zone-content').isHidden());
  await select(nodes[1].id);
  await page.locator('#review-step-name').fill('补充手牌');
  await page.locator('#review-step-notes').fill('先补充资源，再完成通常召唤。');
  assert.match(await page.locator('#review-steps [aria-current=step]').innerText(),/Step 2/);
  await select('final');
  await page.locator('#review-step-notes').fill('终场验收：保留怪兽作为后续资源。');
  const draftBefore=await page.evaluate(()=>JSON.stringify({draft:flow.draft,node:reviewUI.node}));
  await page.locator('#module-home').click();
  await page.waitForFunction(()=>moduleUI.current==='home'&&!moduleUI.switching);
  await page.locator('#home-decks').click();
  await page.waitForFunction(()=>moduleUI.current==='decks'&&!moduleUI.switching);
  await page.locator('#module-expansion').click();
  await page.waitForFunction(()=>moduleUI.current==='expansion'&&!moduleUI.switching);
  assert.equal(await page.evaluate(()=>JSON.stringify({draft:flow.draft,node:reviewUI.node})),draftBefore);
  assert.equal(await page.locator('#review-step-notes').inputValue(),'终场验收：保留怪兽作为后续资源。');
  const drawnIds=new Set(report.events.filter(e=>e.message===90&&e.id!==report.initial_hand_ref).flatMap(e=>e.cards.map(c=>c.instance_id)));
  const randomHand=report.final_state.cards.filter(c=>c.controller===0&&c.location===2&&drawnIds.has(c.instance_id));
  assert(randomHand.length>0,'Real effect draws must reach the final hand');
  assert.equal(await page.locator('.own-board .review-hand .random-card').count(),randomHand.length);
  await page.locator('.own-board .review-hand .random-card').first().scrollIntoViewIfNeeded();
  const before=await page.evaluate(()=>({scroll:scrollY,node:reviewUI.node}));
  await page.locator('.own-board .review-hand .random-card').first().click();
  assert.deepEqual(await page.evaluate(()=>({scroll:scrollY,node:reviewUI.node})),before);
  assert.match(await page.locator('#review-card-detail').innerText(),/随机抽牌/);
  assert.equal(await page.locator('#review-card-detail img').getAttribute('src'),'/review-back.svg');
  const geometry=await page.locator('#review-card-popover').evaluate(el=>{const r=el.getBoundingClientRect();return {inside:r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight,fixed:getComputedStyle(el).position==='fixed'};});
  assert(geometry.inside&&geometry.fixed,'Card details stay inside the viewport near the clicked card');
  await page.screenshot({path:path.join(evidence,'review-random-popover.png'),preserveScroll:true});
  await page.keyboard.press('Escape');assert(await page.locator('#review-card-popover').isHidden());
  const monster=report.final_state.cards.find(c=>c.controller===0&&c.location===4);
  assert(monster);
  await page.evaluate(id=>{
    const button=[...document.querySelectorAll('.own-board .monster-slot [data-review-card]')].find(b=>reviewUI.cards.get(b.dataset.reviewCard).card.instance_id===id);
    button.click();
  },monster.instance_id);
  assert.match(await page.locator('#review-card-detail').innerText(),/通常召唤/);
  assert.match(await page.locator('.detail-effect').innerText(),new RegExp(report.catalog[monster.code].desc.slice(0,3)));
  await page.locator('#review-final-mark').check();
  await page.locator('#review-card-note').fill('终场此卡：实例注释保存验收');
  await page.locator('#review-detail-close').click();
  await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
  const scrolled=await page.evaluate(()=>scrollY);
  await page.locator('#review-log-edge-toggle').click();
  assert.equal(await page.evaluate(()=>scrollY),scrolled,'The edge toggle opens without jumping back to the top');
  await page.locator('[data-log-mode="compact"]').click();
  assert(await page.locator('.log-action .review-card').count()>0);
  const logCard=page.locator('.log-action .review-card').first();await logCard.scrollIntoViewIfNeeded();
  const logContext=await page.evaluate(()=>({node:reviewUI.node,scroll:scrollY,log:document.querySelector('.log-scroll').scrollTop}));
  await logCard.click();
  assert.deepEqual(await page.evaluate(()=>({node:reviewUI.node,scroll:scrollY,log:document.querySelector('.log-scroll').scrollTop})),logContext);
  await page.keyboard.press('Escape');assert(await page.locator('#review-card-popover').isHidden());assert(await page.locator('#review-log').isVisible());
  await page.screenshot({path:path.join(evidence,'review-board-log.png'),preserveScroll:true});
  await page.locator('#review-log-edge-toggle').click();
  assert.equal(await page.evaluate(()=>scrollY),scrolled);
  await page.locator('#save-plan').click();
  await page.waitForFunction(()=>app.view==='confirmation'&&!flow.busy);
  assert.equal(await page.evaluate(async id=>(await api('/api/plans')).some(p=>p.id===id),report.id),false);
  assert.match(await page.locator('#save-confirmation').innerText(),/终场此卡：实例注释保存验收/);
  assert.equal(await page.locator('#save-confirmation .marked-final-cards .review-card').count(),1);
  assert.equal(await page.locator('#save-confirmation .marked-final-cards .random-card').count(),0);
  await page.evaluate(id=>[...document.querySelectorAll('#save-confirmation [data-review-card]')].find(b=>reviewUI.cards.get(b.dataset.reviewCard).card.instance_id===id).click(),monster.instance_id);
  assert.equal(await page.locator('#review-card-note').inputValue(),'终场此卡：实例注释保存验收');
  assert(await page.locator('#review-card-note').isDisabled());
  await page.locator('#review-detail-close').click();
  await page.screenshot({path:path.join(evidence,'review-confirmation.png')});
  await page.locator('#back-to-review').click();
  await select(nodes[1].id);
  assert.equal(await page.locator('#review-step-name').inputValue(),'补充手牌');
  assert.equal(await page.locator('#review-step-notes').inputValue(),'先补充资源，再完成通常召唤。');
  await select('final');
  assert.equal(await page.locator('#review-step-notes').inputValue(),'终场验收：保留怪兽作为后续资源。');
  assert.equal(engineWrites,0,'Reviewing must never run or rewind the engine');
  page.off('request',observer);
  pass('Recorded states, random card backs in hand and confirmation, anchored card details without scroll or node jumps, fixed log toggle, notes and return from confirmation');
};
